[features]
seeds = false
skip-lint = false

[programs.localnet]
flash_loan_mastery = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
flash_loan_mastery = "1oanfPPN8r1i4UbugXHDxWMbWVJ5qLSN5qzNFZkz6Fg"

[programs.mainnet]
flash_loan_mastery = "1oanfPPN8r1i4UbugXHDxWMbWVJ5qLSN5qzNFZkz6Fg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
